<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>Majo.Logging</PackageId>
        <Version>0.0.2</Version>
        <PackageReleaseNotes>Initial release</PackageReleaseNotes>
        <Authors>Sweety Majo</Authors>
        <Description>A small, centralized logging wrapper for .NET applications.</Description>
        <PackageTags>logging;serilog;logger;log</PackageTags>
        <PackageOutputPath>$(MSBuildProjectDirectory)/../artifacts/nuget</PackageOutputPath>

        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/sweetymajo/Majo.Logging</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PackageProjectUrl>https://github.com/sweetymajo/Majo.Logging</PackageProjectUrl>

        <PackageReadmeFile>README.nuget.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.nuget.md" Pack="true" PackagePath="" />
        <None Include="../LICENSE.txt" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0" PrivateAssets="compile;contentfiles;build;analyzers" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" PrivateAssets="compile;contentfiles;build;analyzers" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" PrivateAssets="compile;contentfiles;build;analyzers" />
    </ItemGroup>

</Project>
